# New ports collection makefile for:   renicerd
# Date created:        31 December 2005
# Whom:                drumbsd
#
# $FreeBSD$
#

PORTNAME=      renicerd
PORTVERSION=   1.0
CATEGORIES=    sysutils
MASTER_SITES=  ftp://ftp.cs.columbia.edu/archives/X11R5/contrib/

MAINTAINER=    dpphln@tin.it
COMMENT=       An autorenicerd daemon

.include <bsd.port.mk>
